### PR TITLE
Change 'rand-int' to 'shuffle' to match code

### PR DESCRIPTION
**Pull request by paulhenrich**
Nice writeup. Enjoying working through it with spacemacs. Found just a couple minor things so far.

### CODE REVIEW

**Comment by paulhenrich** [comment]
I _think_ the condition in walk-chain:

``` clojure
(if (>= new-result-char-count 140)
          result...
```

can just be >. If it is equal, recur as normal because we know it will fit exactly after the next recursion.

**Comment by paulhenrich** [comment]
I successfully deployed my bot to heroku, learning a lot in the process. :+1:

**Comment by paulhenrich** [comment]
Also let me know if you would like credit or to avoid infamy wrt my bot repo.

**Comment by gigasquid** [comment]
Glad you got your bot up and running. Thanks for the feedback.  I am ok with either credits or not :)

**Pull request merged**
